### ISSUE TITLE
Update USA-NPN in more places

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/ppo-data-interface#9]
From Ellen: I already asked John to fix this and he might have it on his list already, but mentioning it again here... In all places seen by the public, we should use "USA-NPN" instead of NPN. This includes the source field in the downloaded file, the "Title" in the EZID page, and in the quality measurement "USA-NPN term" definition.

**Comment by jdeck88** [comment]
I fixed this in the EZID page and in the downloaded file.

Still todo:
1. the returned results (table view) it still says "NPN"... i need to re-load data indexes to update.
2. Ellen: What is the quality measurement "USA-NPN term" definition?

**Comment by edenny** [comment]
I can't find it in the PPO at the moment (looking in Protege). It was on one of the early spreadsheets of Brian's that I reviewed, but it might have been dropped. If Brian does not know where this is, then I think we don't need to worry about it!

**Comment by jdeck88** [comment]
OK, just fixed the NPN mentions in the data as well, updating all source mentions to USA-NPN.

Let me know if you see any more mentions of just NPN but sounds like we have this covered....
